// pack.ts
// Generate the companion assets (CSS, demo HTML, JSON) and a downloadable .zip.
import JSZip from 'jszip'
import type { GlyphMeta } from './types'

export function generateCss(family: string, meta: GlyphMeta[]): string {
  const L: string[] = []
  L.push(`@font-face {`)
  L.push(`  font-family: '${family}';`)
  L.push(`  src: url('${family}.woff') format('woff'),`)
  L.push(`       url('${family}.ttf') format('truetype');`)
  L.push(`  font-weight: normal;`)
  L.push(`  font-style: normal;`)
  L.push(`  font-display: block;`)
  L.push(`}`)
  L.push(``)
  L.push(`.${family} {`)
  L.push(`  font-family: '${family}' !important;`)
  L.push(`  font-weight: normal;`)
  L.push(`  font-style: normal;`)
  L.push(`  font-variant: normal;`)
  L.push(`  text-rendering: auto;`)
  L.push(`  line-height: 1;`)
  L.push(`  -webkit-font-smoothing: antialiased;`)
  L.push(`}`)
  for (const g of meta) {
    L.push(``)
    L.push(`.${g.cssClass}::before {`)
    L.push(`  content: "\\${g.unicode}";`)
    L.push(`}`)
  }
  return L.join('\n') + '\n'
}

function toBase64(bytes: Uint8Array): string {
  let bin = ''
  const chunk = 0x8000
  for (let i = 0; i < bytes.length; i += chunk) {
    bin += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, i + chunk)))
  }
  return btoa(bin)
}

export function generateHtml(family: string, meta: GlyphMeta[], ttf: Uint8Array): string {
  const dataUri = `data:font/ttf;base64,${toBase64(ttf)}`
  const items = meta.map(g => {
    const ch = String.fromCodePoint(parseInt(g.unicode, 16))
    return `      <li><span class="ic ${family}-${g.name}"></span><code>${g.cssClass}</code><code>0x${g.unicode}</code></li>`
  }).join('\n')
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${family} icon font</title>
<style>
  @font-face {
    font-family: '${family}';
    src: url('${dataUri}') format('truetype');
    font-weight: normal; font-style: normal;
  }
  body { font-family: system-ui, sans-serif; padding: 24px; color: #222; }
  h1 { font-size: 20px; }
  ul { list-style: none; display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 12px; padding: 0; }
  li { border: 1px solid #eee; border-radius: 8px; padding: 12px; text-align: center; }
  .ic { font-family: '${family}'; font-size: 40px; display: block; margin-bottom: 8px; color: #111; }
  code { display: block; font-size: 11px; color: #888; }
</style>
</head>
<body>
<h1>${family} — ${meta.length} icons</h1>
<ul>
${items}
</ul>
</body>
</html>
`
}

export function generateJson(family: string, em: number, meta: GlyphMeta[]): string {
  const icons = meta.map(g => ({
    name: g.name,
    cssClass: g.cssClass,
    codepoint: g.codepoint,
    unicode: '0x' + g.unicode,
  }))
  return JSON.stringify({ family, em, icons }, null, 2) + '\n'
}

export async function packageZip(
  family: string,
  meta: GlyphMeta[],
  em: number,
  ttf: Uint8Array,
  woff: Uint8Array,
  css: string,
  html: string,
  json: string
): Promise<Blob> {
  const zip = new JSZip()
  zip.file(`${family}.css`, css)
  zip.file(`${family}.html`, html)
  zip.file(`${family}.json`, json)
  zip.file(`${family}.ttf`, ttf)
  zip.file(`${family}.woff`, woff)
  const readme = `# ${family}

Generated by IconBake — bake images into an icon font.

## Files
- ${family}.woff / ${family}.ttf — the font
- ${family}.css — @font-face + .${family}-<name>::before rules
- ${family}.html — standalone preview (font embedded)
- ${family}.json — name → codepoint map

## Usage
\`\`\`html
<link rel="stylesheet" href="${family}.css">
<span class="${family}-${meta[0]?.name ?? 'icon'}"></span>
\`\`\`
`
  zip.file('README.md', readme)
  return zip.generateAsync({ type: 'blob' })
}
